# Generated by Django 4.2.2 on 2023-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('default', '0003_patient_is_active_patient_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='patient_set', related_query_name='patient', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='patient_set', related_query_name='patient', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
    ]
