# Generated by Django 4.2.2 on 2023-07-14 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0004_patient_groups_patient_is_superuser_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='Birthdate',
            field=models.DateField(null=True),
        ),
    ]
