# Generated by Django 4.2.2 on 2023-07-20 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('default', '0006_doctor_groups_doctor_is_active_doctor_is_staff_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='practice_liscence',
            field=models.ImageField(blank=True, upload_to='doctor_profiles/'),
        ),
    ]
